### ISSUE TITLE
Why is signing the hash and not the payload a pitfall?

### ISSUE THREAD

**Issue by chaosite** [yuvadm/greenpass#1]
Isn't that a best practice?

**Comment by yuvadm** [comment]
Simply, it's an unnecessary complication that adds no value to the signature scheme and only causes confusion to developers.

**Comment by chaosite** [comment]
But if you sign the actual payload, then you have to deal with padding manually, and you're not guaranteed that the signature will always be the same size and so on...

But reading the code, it seems that what you mean is that the message is actually hashed _twice_? First manually, then as part of the signing operation?

**Comment by yuvadm** [comment]
Padding is handled by PKCS#1 v1.5, and you correct, about the double hashing. We'll clarify that in the README.

The crux of the issue is that most crypto APIs will handle padding and hashing for you, given a pub key, payload and a signature to verify. This is true in Python cryptography, in openssl, and in any other common crypto library.

So yes, the extra hashing step is redundant.
